/* eslint-disable react-refresh/only-export-components */
import { createContext, useState, useEffect, useContext } from 'react';

const LanguageContext = createContext();

const translations = {
  en: {
    appTitle: "Elections 2026: Stance Alignment",
    appSubtitle: "Find out which party matches your stances on major national issues.",
    welcomeHeader: "Where Do You Stand?",
    copyrightsReserved: "© 2026 All Rights Reserved",
    startQuiz: "Start Stance Quiz",
    exploreParties: "Explore Parties",
    questionProgress: "QUESTION {current} OF {total}",
    stronglyAgree: "Strongly Agree",
    agree: "Agree",
    disagree: "Disagree",
    stronglyDisagree: "Strongly Disagree",
    back: "Back",
    calculateResults: "Calculate Results",
    yourBestMatch: "YOUR BEST MATCH",
    stanceAlignment: "STANCE ALIGNMENT",
    detailedBreakdown: "Detailed Stance Comparison",
    selectPartyCompare: "Compare Stances With:",
    issue: "Issue",
    yourStance: "Your Stance",
    partyStance: "Party Stance",
    compatibility: "Match",
    retakeQuiz: "Retake Quiz",
    backToHome: "Back to Home",
    partyDatabase: "Political Party Profiles",
    leader: "Leader",
    platformStances: "Platform Stances",
    history: "History",
    strengths: "Strengths & Platform",
    challenges: "Challenges & Criticisms",
    noOpinion: "No Opinion / Neutral",
    neutralStance: "Neutral Stance",
    viewPlatform: "View Platform Stances",
    highlyAligned: "Highly Aligned",
    partialMatch: "Partial Match",
    opposedStance: "Opposed Stance",
    security: "Security & Draft",
    religion_state: "Religion & State",
    judicial: "Judicial System",
    economy: "Economy & Welfare",
    selectStatement: "Which statement aligns more with your views?",
    statementA: "Statement A",
    statementB: "Statement B",
    compareWith: "Compare with:",
    compareStances: "Compare Stances",
    accessibilityTitle: "Accessibility Settings",
    accessibilityButton: "Accessibility Settings Menu",
    highContrast: "High Contrast",
    darkContrast: "Dark Contrast",
    monochrome: "Monochrome Mode",
    fontSize: "Font Size",
    fontSizeSmall: "Small",
    fontSizeMedium: "Medium",
    fontSizeLarge: "Large",
    dyslexiaFont: "Dyslexia-Friendly Font",
    reducedMotion: "Reduced Motion / Animations",
    accessibilityStatement: "Accessibility Statement",
    close: "Close",
    resetSettings: "Reset Settings",
    accStatementTitle: "Accessibility Statement",
    accStatementBody: "We are committed to making this platform accessible to all users, in accordance with the Equal Rights for Persons with Disabilities Law in Israel. We have made every effort to ensure that the site meets level AA criteria of the Web Content Accessibility Guidelines (WCAG 2.1).",
    accCoordinator: "Accessibility Coordinator",
    accCoordinatorName: "David Cohen",
    accCoordinatorEmail: "accessibility@ballotbox2026.org.il",
    accCoordinatorPhone: "+972-3-555-0199",
    accLastUpdated: "Last Updated: May 2026",
    considerVotingQuestion: "Is this the party you considered voting for?",
    yes: "Yes",
    no: "No",
    maybe: "Maybe / Unsure",
    feedbackReceived: "Thanks for your feedback!",
    adminDashboard: "Admin Dashboard",
    adminTokenPrompt: "Enter Administrator Access Token",
    adminTokenPlaceholder: "Enter token...",
    submitToken: "Authorize",
    invalidToken: "Invalid or unauthorized token.",
    sqlQueryPlaceholder: "Enter SQL read query (e.g. SELECT * FROM sessions;)",
    runQuery: "Run SQL Query",
    quickQueries: "Quick Queries",
    sessionsTable: "Sessions Table",
    actionsTable: "Actions Table",
    topMatchesSummary: "Match Summary",
    actionDistributionSummary: "Action Distribution",
    unauthorized: "Unauthorized access. Please log in.",
    noResults: "No records found.",
    errorOccurred: "An error occurred during query execution",
    statsOverview: "Stats Overview",
    startedCount: "Sessions Started",
    completedCount: "Sessions Completed",
    conversionRateLabel: "Completion Rate",
    avgScoreLabel: "Average Match Score",
    avgActionsLabel: "Average Actions / Session",
    consideredVotingSummary: "Considered Voting Feedback",
    closeAdmin: "Exit Admin Mode",
    nameSelectionTitle: "Identity Setup",
    nameSelectionLabel: "Enter a display name to track your session results, or proceed anonymously.",
    nameSelectionPlaceholder: "Enter a name...",
    regenerateAlias: "Regenerate Alias ↻",
    proceedWithName: "Start Quiz with this name",
    skipAnonymous: "Skip & Answer Anonymously",
    shareResults: "Share Match Image",
    shareModalTitle: "Share Your Results",
    shareModalSubtitle: "Generate an image formatted for Instagram Stories or other platforms.",
    downloadImage: "Download PNG",
    copyImage: "Copy Image",
    shareImage: "Share Image",
    scanToCompare: "SCAN TO TAKE THE SURVEY",
    brandingText: "ELECTIONS 2026 // SURVEY",
    fallbackModalTitle: "Simulated Share Sheet",
    fallbackModalDesc: "Web sharing is simulated. On mobile devices, this launches the native OS sharing menu.",
    closeModal: "Close"
  },
  he: {
    appTitle: "בחירות 2026: מפתח עמדות",
    appSubtitle: "גלו איזו מפלגה מתאימה ביותר לעמדות שלכם בנושאי מפתח לאומיים.",
    welcomeHeader: "איפה אתם עומדים?",
    copyrightsReserved: "© 2026 כל הזכויות שמורות",
    startQuiz: "התחילו בבוחן העמדות",
    exploreParties: "מאגר המפלגות",
    questionProgress: "שאלה {current} מתוך {total}",
    stronglyAgree: "מסכים מאוד",
    agree: "מסכים",
    disagree: "לא מסכים",
    stronglyDisagree: "מתנגד בתוקף",
    back: "חזור",
    calculateResults: "חשב תוצאות",
    yourBestMatch: "ההתאמה הטובה ביותר עבורכם",
    stanceAlignment: "התאמה רעיונית",
    detailedBreakdown: "השוואת עמדות מפורטת",
    selectPartyCompare: "השווה עמדות עם:",
    issue: "נושא",
    yourStance: "העמדה שלכם",
    partyStance: "עמדת המפלגה",
    compatibility: "התאמה",
    retakeQuiz: "בצע בוחן מחדש",
    backToHome: "חזרה למסך הבית",
    partyDatabase: "פרופילי המפלגות בישראל",
    leader: "יושב ראש",
    platformStances: "עמדות רשמיות בנושאי מפתח",
    history: "היסטוריה",
    strengths: "חוזקות ומצע מרכזי",
    challenges: "אתגרים וביקורת ציבורית",
    noOpinion: "ללא דעה / נייטרלי",
    neutralStance: "עמדה נייטרלית",
    viewPlatform: "הצג עמדות מפלגה",
    highlyAligned: "התאמה מלאה",
    partialMatch: "התאמה חלקית",
    opposedStance: "ניגוד עמדות",
    security: "ביטחון וגיוס",
    religion_state: "דת ומדינה",
    judicial: "מערכת המשפט",
    economy: "כלכלה וחברה",
    selectStatement: "איזו קביעה מתאימה יותר לעמדות שלכם?",
    statementA: "קביעה א'",
    statementB: "קביעה ב'",
    compareWith: "השווה עם:",
    compareStances: "השוואת עמדות",
    accessibilityTitle: "הגדרות נגישות",
    accessibilityButton: "תפריט הגדרות נגישות",
    highContrast: "ניגודיות גבוהה",
    darkContrast: "ניגודיות כהה",
    monochrome: "גווני אפור (מונוכרום)",
    fontSize: "גודל גופן",
    fontSizeSmall: "קטן",
    fontSizeMedium: "רגיל",
    fontSizeLarge: "גדול",
    dyslexiaFont: "גופן מותאם לדיסלקציה",
    reducedMotion: "הפחתת אנימציות ותנועה",
    accessibilityStatement: "הצהרת נגישות",
    close: "סגור",
    resetSettings: "איפוס הגדרות",
    accStatementTitle: "הצהרת נגישות",
    accStatementBody: "אנו מחויבים להנגיש את הפלטפורמה לכלל המשתמשים, בהתאם לחוק שוויון זכויות לאנשים עם מוגבלות בישראל. השקענו מאמצים רבים כדי להבטיח שהאתר יעמוד בקריטריונים של רמה AA של ההנחיות לנגישות תכנים באינטרנט (WCAG 2.1).",
    accCoordinator: "רכז נגישות",
    accCoordinatorName: "דוד כהן",
    accCoordinatorEmail: "accessibility@ballotbox2026.org.il",
    accCoordinatorPhone: "03-555-0199",
    accLastUpdated: "עודכן לאחרונה: מאי 2026",
    considerVotingQuestion: "האם זו המפלגה ששקלתם להצביע לה?",
    yes: "כן",
    no: "לא",
    maybe: "אולי / לא בטוח",
    feedbackReceived: "תודה על המשוב!",
    adminDashboard: "לוח בקרה מנהל",
    adminTokenPrompt: "הזינו מפתח גישה למנהל מערכת",
    adminTokenPlaceholder: "הזינו מפתח גישה...",
    submitToken: "אשר גישה",
    invalidToken: "מפתח הגישה שגוי או לא מורשה.",
    sqlQueryPlaceholder: "הזינו שאילתת SQL לקריאה (לדוגמה SELECT * FROM sessions;)",
    runQuery: "הריצו שאילתה",
    quickQueries: "שאילתות מהירות",
    sessionsTable: "טבלת סשנים",
    actionsTable: "טבלת פעולות",
    topMatchesSummary: "סיכום התאמות מפלגות",
    actionDistributionSummary: "התפלגות פעולות",
    unauthorized: "אין הרשאת גישה. אנא התחבר.",
    noResults: "לא נמצאו רשומות.",
    errorOccurred: "שגיאה התרחשה במהלך הרצת השאילתה",
    statsOverview: "סקירת נתונים כללית",
    startedCount: "סשנים שהתחילו",
    completedCount: "סשנים שהושלמו",
    conversionRateLabel: "שיעור השלמה",
    avgScoreLabel: "ממוצע התאמה",
    avgActionsLabel: "ממוצע פעולות לסשן",
    consideredVotingSummary: "משוב התחשבות בהצבעה",
    closeAdmin: "יציאה ממצב מנהל",
    nameSelectionTitle: "הגדרת זהות",
    nameSelectionLabel: "בחרו כינוי כדי לעקוב אחר תוצאות הסשן שלכם, או המשיכו באופן אנונימי.",
    nameSelectionPlaceholder: "הזינו כינוי...",
    regenerateAlias: "החלף כינוי ↻",
    proceedWithName: "התחילו את הבוחן עם שם זה",
    skipAnonymous: "דילוג ומענה אנונימי",
    shareResults: "שתפו תמונת התאמה",
    shareModalTitle: "שיתוף התוצאה שלכם",
    shareModalSubtitle: "צרו תמונה מותאמת לסטורי באינסטגרם או לפלטפורמות אחרות.",
    downloadImage: "הורדת תמונה",
    copyImage: "העתקת תמונה",
    shareImage: "שיתוף תמונה",
    scanToCompare: "סרקו לביצוע הבוחן",
    brandingText: "בחירות 2026 // סקר עמדות",
    fallbackModalTitle: "חלון שיתוף סימולטיבי",
    fallbackModalDesc: "השיתוף הוירטואלי מופעל כאן. במכשירים ניידים, כפתור זה יפתח את תפריט השיתוף הרשמי של מערכת ההפעלה.",
    closeModal: "סגור"
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem('israeli_elections_lang');
    return saved || 'he'; // Default to Hebrew
  });

  const dir = language === 'he' ? 'rtl' : 'ltr';

  useEffect(() => {
    localStorage.setItem('israeli_elections_lang', language);
    document.documentElement.lang = language;
    document.documentElement.dir = dir;
  }, [language, dir]);

  const toggleLanguage = () => {
    setLanguage((prev) => (prev === 'he' ? 'en' : 'he'));
  };

  const t = (key, params = {}) => {
    let text = translations[language][key] || translations['en'][key] || key;
    Object.keys(params).forEach((param) => {
      text = text.replace(`{${param}}`, params[param]);
    });
    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, dir, t, toggleLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
